CREATE DATABASE QuanLySV USE QuanLySV; CREATE TABLE SV (     MASV INT PRIMARY KEY,     HO VARCHAR(50),     TEN VARCHAR(50),     TenLop VARCHAR(50) );  INSERT INTO SV(MASV, HO, TEN, TenLop) VALUES (345, 'Bui', 'Lan', 'CN02'), (873, 'Vu', 'Lan', 'CN01'), (693, 'Tran', 'Lan', 'CN02'), (999, 'Bui', 'Kim Cuong', 'CN01'), (998, 'Tran', 'Hai Nam', 'CN01') SELECT * FROM SV -- Bai 3: UPDATE SV
SET TenLop = 'CN02'
WHERE MASV = 873;
SELECT * FROM SV WHERE MASV = 873

-- Bai 4:
DELETE FROM SV WHERE HO = 'Bui'
SELECT * FROM SV WHERE HO = 'Bui'

-- Bai 5:
ALTER TABLE SV
ADD DIEM int check(Diem BETWEEN 0 AND 10)

-- Bai 6:
ALTER TABLE SV
ALTER COLUMN TenLop nchar(20);

-- Bai 7:
SELECT * FROM SV WHERE TenLop = 'CN02';
SELECT HO, TEN FROM SV;
SELECT HO, TEN FROM SV WHERE TenLop = 'CN02';
SELECT TenLop, Count(*) AS SoSinhVien FROM SV
GROUP BY TenLop

SELECT TenLop FROM SV 
GROUP BY TenLop
HAVING COUNT(*)>=2;

ALTER TABLE SV
ADD DiaChi nchar(20)
SELECT * FROM SV
UPDATE SV
SET DiaChi = 'Ha Noi'