/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhanviendz;

/**
 *
 * @author Admin
 */
public class Casio extends javax.swing.JFrame {

    /**
     * Creates new form Casio
     */
    public Casio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_so2 = new javax.swing.JTextField();
        txt_so1 = new javax.swing.JTextField();
        button_tru = new javax.swing.JButton();
        button_cong = new javax.swing.JButton();
        button_chia = new javax.swing.JButton();
        button_nhan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        label_kq = new javax.swing.JLabel();
        button_rm = new javax.swing.JButton();
        button_tinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Số 1");

        jLabel2.setText("Số 2");

        button_tru.setText("-");
        button_tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_truActionPerformed(evt);
            }
        });

        button_cong.setText("+");
        button_cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_congActionPerformed(evt);
            }
        });

        button_chia.setText(":");
        button_chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_chiaActionPerformed(evt);
            }
        });

        button_nhan.setText("x");
        button_nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nhanActionPerformed(evt);
            }
        });

        jLabel3.setText("Kết quả:");

        label_kq.setText("Đang chờ nhập");

        button_rm.setText("Xóa hết");
        button_rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_rmActionPerformed(evt);
            }
        });

        button_tinh.setText("Tính");
        button_tinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_so1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_so2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_cong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_tru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_nhan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_chia)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_kq))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_tinh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_rm)))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_so1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_so2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_tru)
                    .addComponent(button_nhan)
                    .addComponent(button_chia)
                    .addComponent(button_cong))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_rm)
                    .addComponent(button_tinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_kq))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String pheptinh = "";
    private void button_truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_truActionPerformed
        // TODO add your handling code here:
        pheptinh = "-";
    }//GEN-LAST:event_button_truActionPerformed

    private void button_congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_congActionPerformed
        // TODO add your handling code here:
        pheptinh = "+";
    }//GEN-LAST:event_button_congActionPerformed

    private void button_chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_chiaActionPerformed
        // TODO add your handling code here:
        pheptinh = ":";
    }//GEN-LAST:event_button_chiaActionPerformed

    private void button_nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nhanActionPerformed
        // TODO add your handling code here:
        pheptinh = "x";
    }//GEN-LAST:event_button_nhanActionPerformed

    private void button_rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_rmActionPerformed
        // TODO add your handling code here:
        txt_so1.setText("");
        txt_so2.setText("");
    }//GEN-LAST:event_button_rmActionPerformed

    private void button_tinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tinhActionPerformed
        // TODO add your handling code here:
        int kq = 0;
        int so1 = Integer.parseInt(txt_so1.getText());
        int so2 = Integer.parseInt(txt_so2.getText());
        
        if(pheptinh.equals("+")) {
            kq = so1 + so2;
        } else if(pheptinh.equals("-")) {
            kq = so1 - so2;
        } else if(pheptinh.equals("x")) {
            kq = so1 * so2;
        } else if(pheptinh.equals(":")) {
            kq = so1 / so2;
        }
        label_kq.setText(String.valueOf(kq));
    }//GEN-LAST:event_button_tinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Casio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_chia;
    private javax.swing.JButton button_cong;
    private javax.swing.JButton button_nhan;
    private javax.swing.JButton button_rm;
    private javax.swing.JButton button_tinh;
    private javax.swing.JButton button_tru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_kq;
    private javax.swing.JTextField txt_so1;
    private javax.swing.JTextField txt_so2;
    // End of variables declaration//GEN-END:variables
}
