/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testnow;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class MayTinhView extends javax.swing.JFrame {

    /**
     * Creates new form MayTinhView
     */
    ThongTinMayTinh mt = new ThongTinMayTinh();
    
    public MayTinhView() {
        initComponents();
    }


    void load(ArrayList<MayTinh> list) {
        DefaultTableModel tb = (DefaultTableModel) tbn.getModel();
        tb.setRowCount(0);
        for(MayTinh data : list) {
            tb.addRow(new Object[] {
                data.getId(),
                data.getHang(),
                data.getCpu(),
                data.getGpu(),
                data.getGia(),
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbn = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_rm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_id = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_hang = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_cpu = new javax.swing.JTextPane();
        rd_co = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rd_ko = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_gia = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        btn_load = new javax.swing.JButton();
        btn_fileadd = new javax.swing.JButton();
        btn_fileread = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Hãng máy", "CPU", "GPU", "Giá"
            }
        ));
        tbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbn);

        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edit.setText("Sửa");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_rm.setText("Xóa");
        btn_rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rmActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jScrollPane2.setViewportView(txt_id);

        jLabel2.setText("Hãng");

        jScrollPane3.setViewportView(txt_hang);

        jLabel3.setText("GPU");

        jScrollPane4.setViewportView(txt_cpu);

        buttonGroup1.add(rd_co);
        rd_co.setText("Có");

        jLabel4.setText("CPU");

        buttonGroup1.add(rd_ko);
        rd_ko.setText("Ko");

        jScrollPane5.setViewportView(txt_gia);

        jLabel5.setText("Giá");

        btn_load.setText("Tải dữ liệu");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        btn_fileadd.setText("FIle: add");
        btn_fileadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fileaddActionPerformed(evt);
            }
        });

        btn_fileread.setText("File: read");
        btn_fileread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filereadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rd_co)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd_ko))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_load)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_rm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fileadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fileread)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_add)
                            .addComponent(btn_edit)
                            .addComponent(btn_rm)
                            .addComponent(btn_load)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_fileadd)
                                .addComponent(btn_fileread))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rd_co)
                            .addComponent(rd_ko))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        // TODO add your handling code here:
        load(mt.mt);
    }//GEN-LAST:event_btn_loadActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String hang, cpu, gpu, ret;
        double gia;
        int id;
        id = Integer.parseInt(txt_id.getText());
        hang = txt_hang.getText();
        cpu = txt_cpu.getText();
        if(rd_co.isSelected()) gpu = "có";
        else gpu = "ko";
        gia = Double.parseDouble(txt_gia.getText());
        ret = mt.add(new MayTinh(id, hang, cpu, gpu, gia));
        load(mt.mt);
        JOptionPane.showMessageDialog(this, ret);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        int row = tbn.getSelectedRow();
        MayTinh data = mt.mt.get(row);
        
        String hang, cpu, gpu;
        double gia;
        int id;
        id = Integer.parseInt(txt_id.getText());
        hang = txt_hang.getText();
        cpu = txt_cpu.getText();
        if(rd_co.isSelected()) gpu = "có";
        else gpu = "ko";
        gia = Double.parseDouble(txt_gia.getText());
        
        mt.mt.set(row, data);
        load(mt.mt);
        JOptionPane.showMessageDialog(this, "Da sua");
    }//GEN-LAST:event_btn_editActionPerformed

    private void tbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnMouseClicked
        // TODO add your handling code here:
        int row = tbn.getSelectedRow();
        MayTinh data = mt.mt.get(row);
        
        txt_id.setText(String.valueOf(data.getId()));
        txt_hang.setText(data.getHang());
        txt_cpu.setText(data.getCpu());
        txt_gia.setText(String.valueOf(data.getGia()));
        if(data.getGpu().equals("có")) {
            rd_co.setSelected(true);
        } else {
            rd_ko.setSelected(true);
        }
    }//GEN-LAST:event_tbnMouseClicked

    private void btn_rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rmActionPerformed
        // TODO add your handling code here:
        int row = tbn.getSelectedRow();
        MayTinh data = mt.mt.get(row);
        
        mt.mt.remove(data);
        JOptionPane.showMessageDialog(this, "Da xoa");
        load(mt.mt);
    }//GEN-LAST:event_btn_rmActionPerformed

    private void btn_fileaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fileaddActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter file = new FileWriter("data.txt");
            BufferedWriter buf = new BufferedWriter(file);
            ArrayList<MayTinh> mtlist = mt.mt;
            
            System.out.print("PROCCED");
            for(MayTinh list : mtlist) {
                System.out.println("IN" + list);
                buf.write(list.toString());
                buf.newLine();
            }
            buf.flush();
            System.out.print("DONE");
            buf.close();
        } catch(Exception e) {
            
        }
        
    }//GEN-LAST:event_btn_fileaddActionPerformed

    private void btn_filereadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filereadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_filereadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MayTinhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MayTinhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MayTinhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MayTinhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MayTinhView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_fileadd;
    private javax.swing.JButton btn_fileread;
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_rm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rd_co;
    private javax.swing.JRadioButton rd_ko;
    private javax.swing.JTable tbn;
    private javax.swing.JTextPane txt_cpu;
    private javax.swing.JTextPane txt_gia;
    private javax.swing.JTextPane txt_hang;
    private javax.swing.JTextPane txt_id;
    // End of variables declaration//GEN-END:variables
}
